### ISSUE TITLE
Fails to copile with Carthage

### ISSUE THREAD

**Issue by fnc12** [RedMadRobot/input-mask-ios#19] opened 2017-08-21 07:22 UTC
Cartfile:
```
git "https://github.com/RedMadRobot/input-mask-ios.git"
```

Command: `carthage update --platform ios`

Output: 
```
*** Building scheme "InputMask" in InputMask.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/johnzakharov/Desktop/Xcode/crediton-ios/Carthage/Checkouts/input-mask-ios/Source/InputMask/InputMask.xcodeproj -scheme InputMask -configuration Release -derivedDataPath /Users/johnzakharov/Library/Caches/org.carthage.CarthageKit/DerivedData/input-mask-ios/3.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build (launched in /Users/johnzakharov/Desktop/Xcode/crediton-ios/Carthage/Checkouts/input-mask-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/hz/_y3bdbvn025bv6gk1xqq1_jm0000gn/T/carthage-xcodebuild.IgDgmm.log
```

Log file (inputmask part):
```
/usr/bin/xcrun xcodebuild -project /Users/johnzakharov/Desktop/Xcode/crediton-ios/Carthage/Checkouts/input-mask-ios/Source/InputMask/InputMask.xcodeproj -scheme InputMask -configuration Release -derivedDataPath /Users/johnzakharov/Library/Caches/org.carthage.CarthageKit/DerivedData/input-mask-ios/3.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build (launched in /Users/johnzakharov/Desktop/Xcode/crediton-ios/Carthage/Checkouts/input-mask-ios)User defaults from command line:
    IDEDerivedDataPathOverride = /Users/johnzakharov/Library/Caches/org.carthage.CarthageKit/DerivedData/input-mask-ios/3.0.0

Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.3

=== CLEAN TARGET InputMask OF PROJECT InputMask WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET InputMask OF PROJECT InputMask WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by taflanidi** [comment] 2017-08-21 11:38
@fnc12 hi!
Thanks for your report.

Could you please let me know your IDE version? Looks like you are using an old version of the Xcode, probably 8.2.

**Comment by fnc12** [comment] 2017-08-21 11:50
Version 8.3.3 (8E3004b)

**Comment by hiaw** [comment] 2017-08-22 02:26
I had the same problem then I found that the problem is that it was trying to use Swift 4. The master branch is still using Swift 3 so the following in my `Cartfile` works.

git "https://github.com/RedMadRobot/input-mask-ios.git" "master"

**Comment by taflanidi** [comment] 2017-08-22 07:58
@fnc12 I wasn't able to reproduce your issue yet. Still digging into it.

Meanwhile, have you tried @hiaw's advice? Did it help?

**Comment by fnc12** [comment] 2017-08-22 07:59
I use swift 3 in this project.

**Comment by taflanidi** [comment] 2018-04-28 14:38
Closing as outdated; feel free to reopen if still relevant.

**Closed by taflanidi** 2018-04-28 14:38 UTC
Labels: circumstances  clarification
