### ISSUE TITLE
Brazilian Phones

### ISSUE THREAD

**Issue by cs-joao-souza** [RedMadRobot/input-mask-ios#8] opened 2017-04-28 14:14 UTC
Here in brazil we have a problem that cell phones there are 9 digits and landlines have 8 digits.
We can solve that using affineFormats from PolyMaskTextFieldDelegate but there is a problem, that is not automatically.

`self.phonePolyMaskTextFieldDelegate?.affineFormats = [ "([00]) [00000]-[0000]", "([00]) [0000]-[0000]"]`

Im using like this. But if i have an 8 digits phone, i do need to type the "-" to force the textfield be 8 digits. Is there any way to do it automatically? Like, if my phone have 8 digits, it stays with the mask ([00]) [0000]-[0000] and if i need to put 9 digits the "-" automatically changes.

**Comment by fernandudouglas** [comment] 2017-04-28 14:27
I solved this as follows:
First step:
`var telephoneMask: MaskedTextFieldDelegate!`

Second step:
I created a method that I call it in my ViewDidLoad, called ApplyMaskInFields.

Within my method, I have the following code to apply the mask in the phone field:

```
TelephoneMask = MaskedTextFieldDelegate (format: "([00]) [000000000]")
TelephoneMask.listener = self
TelephoneTextField.delegate = telephoneMask
TelephoneMask.put (text: "", into: telephoneTextField)
```

I practically did the same with the CPF, but changed the format as follows:
`CpfMask = MaskedTextFieldDelegate (format: "[000]. [000]. [000] - [00]")`

Is that what you needed?

**Comment by cs-joao-souza** [comment] 2017-04-28 14:34
Is kind of this. If i have more than one textField that needs to be a phone i would repeat code. That's not what i want. I'm using the mask with hifen ("-") and some optional values. You use 9 digits optionals. So it works. But if i have the hifen i do need to type this if my mask is different from the default mask.

can u understand me?

**Comment by fernandudouglas** [comment] 2017-04-28 14:39
Could you explain better?
Are you required to use a hyphen in the field?
It would be interesting to leave an example of the problem you are having and so I will try to help you!

**Comment by cs-joao-souza** [comment] 2017-04-28 14:47
Yes, im sorry about "hifen". But the hyphen is required. 

I have a text field. And i do need to have a mask. With DDD and the phone number.
But in brazil as you know we have 44 98888-0000 for cell phones and 42 3456-9090 for landlines.

I can solve this using affineFormats from PolyMaskTextFieldDelegate. But, imagine if i write 42 3456-9090 and i forgot that my phone has another number, so i need to type it. Using inputmask im not able to type it and i need to delete all the text and start to type again and i that case i need to type the hyphen to make PolyMaskTextFieldDelegate understand that is the other mask that i want. It would be great, if the textField did it automatically based on all formats. So, when i have 42 3456-9090 and type more one number like 8, all numbers would be left shifted and would stay like this 44 34560-9098.

**Comment by taflanidi** [comment] 2017-04-29 15:43
Hey @cs-joao-souza!
Thanks for your question.

I'll come back to you a bit later w/ explanations.

**Comment by cs-joao-souza** [comment] 2017-04-29 16:10
Thanka @taflanidi. 

Have u got my question?

**Comment by taflanidi** [comment] 2017-05-02 11:43
@cs-joao-souza, yeah, I think so.

Unfortunately, you won't be able to achieve required behaviour with wildcard mask like `([00]) [00000]-[0000]`, as current affinity calculation algorithm is not designed for it. With a step-by-step iteration over the input string, the affinity is increased or decreased depending on the action to be performed. 

For instance, let us have an input string like

`(01) 2345-6789`

and two formats:

* `([00]) [0000]-[0000]`
* `([00]) [00000]-[0000]`

For this initial setup we will have corresponding affinity numbers:

* `([00]) [0000]-[0000]` ~ **14** == `(` + `01` + `)` + space + `2345` + `-` + `6789`
* `([00]) [00000]-[0000]` ~ **11** == `(` + `01` + `)` + space + `2345` – `–` + `6` – `–` + `789`

Let us add one digit to the initial input string: 

`(01) 2345-67890`

This way, first affinity will be decreased because of the redundant digit and second affinity will increase, but not enough to overcome the first one:

* `([00]) [0000]-[0000]` ~ **13** == `(` + `01` + `)` + space + `2345` + `-` + `6789` – `0`
* `([00]) [00000]-[0000]` ~ **12** == `(` + `01` + `)` + space + `2345` – `–` + `6` – `–` + `7890`

**Still, you may try another approach.**

I don't know the actual situation, so accept my excuses in case I'm wrong. 
According to [ITU](https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200001D0003PDFE.pdf), GSM/mobile phone numbers will all have `9` following the area code:

`(xx) 9xxxx-xxxx`

and fixed/radio phone numbers will have `7`, `2`, `3`, `4` or `5`  following the area code:

`(xx) 7xxx-xxxx`

You may define a set of mask formats to distinguish long mobile numbers from short fixed numbers:
```
([00]) {9}[0000]-[0000]
([00]) {2}[000]-[0000]
([00]) {3}[000]-[0000]
([00]) {4}[000]-[0000]
([00]) {5}[000]-[0000]
([00]) {7}[000]-[0000]
```
— such that, the mask switches format on the third digit:

`(11) 9...` == `okay, we've got a long phone number, switching to the mobile mask format...`
`(11) 7...` == `hey, looks like it's a fixed phone number, switching the format...`

Should you have any questions, please do not hesitate to ask them here.
Hope, this will help.

**Comment by cs-joao-souza** [comment] 2017-05-02 18:46
Hi, as far as i know you are completely correct.
I have never thought in that way. Excellent explanation.

Thanks

**Comment by taflanidi** [comment] 2017-05-02 20:02
@cs-joao-souza no problem.

Please, close this issue if the problem is solved.

**Closed** 2017-05-02 22:17 UTC
Labels: question
